feat: add support for sessions in Renku 1.0
SwissDataScienceCenter/renku-data-services pull request #133
Opened 2024-02-29 07:56 UTC by leafty

WIP

* Adds API endpoints for session environments
* Adds API endpoints for session launchers

2024-03-13 18:05 UTC, mana-alisafaee requested changes
Thanks! Please see my comments.

2024-03-13 18:05 UTC, mana-alisafaee commented on components/renku_data_services/session/db.py
> +        if user.id is None or not user.is_admin:
Should we allow creating envs for a specific project without being an admin? If yes, then it's ok to leave it for a future PR or story. Just make sure not to lose it.

2024-03-13 18:05 UTC, mana-alisafaee commented on components/renku_data_services/session/db.py
> +        if user.id is None or not user.is_admin:
Same goes for updating and deleting envs.

2024-03-14 13:34 UTC, leafty commented on components/renku_data_services/session/db.py
> +                    user=user, project_id=launcher.project_id, scope=Scope.WRITE
Huh? Why? This is checking that the user has the `write` permission on the project.

2024-03-14 13:39 UTC, leafty commented on components/renku_data_services/session/models.py
> +class SessionEnvironment(BaseModel):
Done in 68363c3067e19772b7d849c75979632d96eac6fe.

2024-03-14 14:52 UTC, mana-alisafaee commented on components/renku_data_services/session/db.py
> +                    user=user, project_id=launcher.project_id, scope=Scope.WRITE
We have a special permission for delete which we check when deleting a project. Here should be the same I believe.

2024-03-14 15:00 UTC, leafty commented on components/renku_data_services/session/db.py
> +                    user=user, project_id=launcher.project_id, scope=Scope.WRITE
NO! I am removing a session launcher, not the project itself.

2024-03-14 15:05 UTC, leafty commented on components/renku_data_services/session/db.py
> +        authorized = await self.project_authz.has_permission(user=user, project_id=project_id, scope=Scope.READ)
```suggestion
        authorized = await self.project_authz.has_permission(user=user, project_id=project_id, scope=Scope.WRITE)
```

2024-03-14 15:20 UTC, mana-alisafaee approved these changes

2024-03-14 15:41 UTC, merged