feat: API endpoint for repository permissions in connected services
SwissDataScienceCenter/renku-data-services pull request #197
Opened 2024-05-13 11:05 UTC by leafty

WIP

/deploy #notest renku-ui=build/connected-services-final renku-notebooks=leafty/build-connected-services renku=release-0.52.x

2024-05-13 11:36 UTC, Panaetius requested changes
looks all good, just two minor comments

2024-05-13 11:36 UTC, Panaetius commented on components/renku_data_services/migrations/versions/788840ccdcf4_add_connected_services.py
> +        sa.Column('client_secret', sa.LargeBinary(), nullable=True),
Formatting error? should be double quotes

2024-05-13 11:36 UTC, Panaetius commented on test/components/renku_data_services/connected_services/test_encryption.py
> +def admin_api_user() -> APIUser:
we already have an admin_user fixture in conftest that can be reused

2024-05-31 16:05 UTC, olevski requested changes
Thanks for implementing this Flora.

As I mentioned in the comments below and when we discussed. I dont think we should mix the oauth functionality with the git/repository functionality, and we should separate the git/repository stuff into its own module. I think this can be done by just moving some of the methods and models you have here in the `components/renku_data_services/git` module.

2024-05-31 16:46 UTC, leafty commented on components/renku_data_services/connected_services/external_models.py
> +class GitLabConnectedAccount(BaseModel):
This is not an internal model, I use validation to validate the json response from GitLab API.

2024-05-31 16:48 UTC, leafty commented on components/renku_data_services/connected_services/utils.py
> +        url = f"{repository_url}/info/refs?service=git-upload-pack"
This works for HTTP git repositories. It follows the http protocol for git.

I don't think we can support the ssh protocol for now.

2024-05-31 16:49 UTC, leafty commented on components/renku_data_services/connected_services/utils.py
> +async def probe_repository(repository_url: str) -> bool:
I don't think a test should hit the network.

2024-05-31 16:50 UTC, leafty commented on components/renku_data_services/connected_services/utils.py
> +async def probe_repository(repository_url: str) -> bool:
* the wider internet, as opposed to local dev container services

2024-05-31 16:52 UTC, leafty commented
@olevski this is an important feature for Renku 2.0, I do not think there is dependency for short-term work on this, but it is still a core feature of Renku 2.0.

2024-05-31 16:59 UTC, leafty commented on components/renku_data_services/connected_services/api.spec.yaml
> +  /oauth2/api/repositories/{repository_url}/probe:
This is not really how this works. The first endpoint only supports git repositories hosted by one of the listed providers. This one is about checking if the repo is likely clonable by checking if it answers on the git https protocol.

2024-05-31 17:00 UTC, leafty commented on components/renku_data_services/connected_services/db.py
> +    ) -> models.RepositoryProviderMatch | Literal["304"]:
This is not an easy decoupling, as the second part of the code uses the Authlib client configured from the first part.

2024-06-03 07:38 UTC, olevski commented on components/renku_data_services/connected_services/api.spec.yaml
> +  /oauth2/api/repositories/{repository_url}/probe:
I see. Can you please clarify this in the docstrings of the methods for these endpoints in the blueprint?

2024-06-03 07:47 UTC, olevski commented on components/renku_data_services/connected_services/utils.py
> +        url = f"{repository_url}/info/refs?service=git-upload-pack"
There is no validation for the URL of a repo when a project is created in the backend. So we should add that in. I think you can specify a format in the apispec and that will generate the right validation for pydantic. I think the ui expects a valid url, in testing when I added a SSH url in the CI deployment the ui crashed.

2024-06-03 07:49 UTC, olevski commented
@leafty we can do the refactoring I mentioned at a later time. If you resolve the rest of the comments we can merge this.

2024-06-03 07:55 UTC, leafty commented on components/renku_data_services/connected_services/api.spec.yaml
> +  /oauth2/api/repositories/{repository_url}:
Done in 429765aaa8e4fe29db552afbdb91d4eb38d10ba8.

2024-06-03 07:58 UTC, leafty commented on components/renku_data_services/connected_services/utils.py
> +        url = f"{repository_url}/info/refs?service=git-upload-pack"
What I mean to say is: we cannot probe `git+ssh` repositories (for now). I would avoid adding support for that if it means adding a SSH or git module to the code base.

They may be clonable or not, we don't know. The UI will be fixed.

2024-06-03 07:58 UTC, leafty commented on components/renku_data_services/connected_services/external_models.py
> +    PUBLIC_VISIBILITY: ClassVar[str] = "public"
Done in 429765aaa8e4fe29db552afbdb91d4eb38d10ba8.

2024-06-03 07:59 UTC, leafty commented on components/renku_data_services/connected_services/external_models.py
> +    INTERNAL_VISIBILITY: ClassVar[str] = "internal"
Done in 429765aaa8e4fe29db552afbdb91d4eb38d10ba8.

2024-06-03 07:59 UTC, leafty commented on components/renku_data_services/connected_services/dummy_async_oauth2_client.py
> +        print(f"URL = {url}")
Done in 429765aaa8e4fe29db552afbdb91d4eb38d10ba8.

2024-06-03 07:59 UTC, leafty commented on components/renku_data_services/connected_services/blueprints.py
> +    def get_one_repository(self) -> BlueprintFactoryResponse:
Done in 429765aaa8e4fe29db552afbdb91d4eb38d10ba8.

2024-06-03 08:04 UTC, leafty commented
@olevski comments should be addressed now.

2024-06-03 11:00 UTC, olevski approved these changes

2024-06-03 12:40 UTC, merged