feat: always send messages in sanic background process
SwissDataScienceCenter/renku-data-services pull request #217
Opened 2024-05-22 13:22 UTC by Panaetius

closes #189

2024-05-27 11:30 UTC, leafty commented on bases/renku_data_services/data_api/main.py
> +    app = Sanic("send_events")  # we need a dummy app for logging to work.  # noqa: F841
Would this work?

```suggestion
   Sanic("send_events")  # we need a dummy app for logging to work.
```

2024-05-27 15:16 UTC, Panaetius commented on bases/renku_data_services/data_api/main.py
> +    app = Sanic("send_events")  # we need a dummy app for logging to work.  # noqa: F841
i can give it a try, just copied that from your earlier PR :slightly_smiling_face:

2024-05-27 15:29 UTC, leafty commented on bases/renku_data_services/data_api/main.py
> +    app = Sanic("send_events")  # we need a dummy app for logging to work.  # noqa: F841
😄 I just pushed the proof of concept for creating a managed background process and how to establish a communication channel. It wasn't production-ready code yet.

My intuition on this is that the logger may want access to `current_app` and that's why the line is needed here, btw.

2024-05-27 16:03 UTC, olevski requested changes
Thanks Ralf just a few minor changes.

2024-05-27 16:03 UTC, olevski commented on test/bases/renku_data_services/data_api/test_projects.py
> -    assert proj_event.name == payload["name"]
This also applies to all the other tests where these kind of checks are removed. Considering we are worried about drifting from the events queue and all its consumers we should test that we are adding the right events in all cases.

2024-05-27 16:10 UTC, Panaetius commented on bases/renku_data_services/data_api/main.py
> +    asyncio.set_event_loop(uvloop.new_event_loop())
It's what sanic uses internally as well and I didn't want to deviate from that

2024-05-27 16:12 UTC, Panaetius commented on bases/renku_data_services/data_api/main.py
> +    app = Sanic("send_events")  # we need a dummy app for logging to work.  # noqa: F841
Right below that line it says: `The simplest method for doing that in Python will be to just wrap your loop in KeyboardInterrupt` which I added here: https://github.com/SwissDataScienceCenter/renku-data-services/pull/217/files#diff-1b9249f808cb3fb3ed6b2320c83439f3efcaca58faf9f93bb52e6ad03e1b301dR36

2024-05-27 16:13 UTC, Panaetius commented on components/renku_data_services/message_queue/db.py
> +        while True:
Maybe I misunderstand, but there is an asyncio.sleep 3 lines below

2024-05-27 16:14 UTC, Panaetius commented on test/components/renku_data_services/message_queue/test_queue.py
> -    await asyncio.sleep(6)
yes I missed that :+1:

2024-05-28 09:17 UTC, olevski commented on bases/renku_data_services/data_api/main.py
> +    app = Sanic("send_events")  # we need a dummy app for logging to work.  # noqa: F841
Sorry I missed that. Its all good then.

2024-05-28 09:20 UTC, olevski commented on components/renku_data_services/message_queue/db.py
> +        while True:
This is what I see in the PR review and there is no sleep:
![image](https://github.com/SwissDataScienceCenter/renku-data-services/assets/16360283/52097583-affe-4983-9f61-600d76efbf0b)

2024-05-29 07:03 UTC, merged