feat: add platform configuration
SwissDataScienceCenter/renku-data-services pull request #285
Opened 2024-06-24 12:14 UTC by leafty

Closes #284.

WIP

2024-07-18 13:44 UTC, olevski requested changes
Thanks Flora, I just have a few questions.

2024-07-18 14:38 UTC, leafty commented on bases/renku_data_services/data_api/main.py
> +        await config.platform_repo.create_initial_config(user=InternalServiceAdmin(id=ServiceAdminId.migrations))
I will create it on `get` if it doesn't exist.

2024-07-19 06:43 UTC, leafty commented on bases/renku_data_services/data_api/main.py
> +        await config.platform_repo.create_initial_config(user=InternalServiceAdmin(id=ServiceAdminId.migrations))
Done in 5e0b309cac94cc2f704959eec4cc8e0150910ff2.

2024-07-23 09:42 UTC, olevski approved these changes

2024-07-23 09:46 UTC, merged