feat: replace sensitive values and allow removing values
SwissDataScienceCenter/renku-data-services pull request #30
Opened 2023-08-29 11:01 UTC by Panaetius

2023-09-07 11:01 UTC, olevski requested changes
I am really confused how setting the value to `<sensitive>` resolves this issue. Shouldn't we be doing more checks when we handle this field? Or does rclone or the ui understand the meaning of this? What happens if someone is "smart" enough to set the field to such a value in a request that is coming from the client?

2023-09-07 11:35 UTC, Panaetius commented on components/renku_data_services/storage_schemas/core.py
> +            return "<sensitive>"
the UI uses the placeholder. It's not rclone specific, just before we removed sensitive values and now we replace them with the placeholders so we know what sensitive values were there

2023-09-07 15:40 UTC, olevski commented on components/renku_data_services/storage_schemas/core.py
> +            return "<sensitive>"
Can you add this in the docstring for the validate_config method (simply that the ui recognizes and depends on the `<sensivitve>` value? I can totally see someone changing the value and not being aware that the UI expects that value.

2023-09-11 07:37 UTC, olevski approved these changes

2023-09-11 09:24 UTC, olevski approved these changes

2023-09-11 09:39 UTC, Panaetius commented on components/renku_data_services/storage_schemas/core.py
>      def validate_config(self, value, provider: str | None):
addressed in https://github.com/SwissDataScienceCenter/renku-data-services/pull/41

2023-09-11 09:58 UTC, olevski approved these changes

2023-09-11 09:58 UTC, merged