fix: allow unsetting storage secrets
SwissDataScienceCenter/renku-data-services pull request #415
Opened 2024-09-19 13:34 UTC by Panaetius

2024-09-19 13:34 UTC, Panaetius commented
This change is part of the following stack:

- #415 ◀

<sub>Change managed by [git-spice](https://abhinav.github.io/git-spice/).</sub>
<!-- gs:navigation comment -->

2024-10-03 07:47 UTC, leafty commented
Note: This is also implemented for data connectors secrets in https://github.com/SwissDataScienceCenter/renku-data-services/pull/413.

2024-10-07 07:46 UTC, leafty requested changes
Code change to `db.py` is good but the schema change is invalid:

2024-10-07 07:46 UTC, leafty commented on components/renku_data_services/storage/api.spec.yaml
> +            - type: 'null'
This is not allowed with the version of OpenAPI we are using:

```
"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 2)","schema":{"loadingURI":"#","pointer":"/definitions/Components/properties/schemas/patternProperties/^[a-zA-Z0-9\\.\\-_]+$"},"instance":{"pointer":"/components/schemas/CloudStorageSecretPost"}}]
```

See how it is done for `data connctors`:
https://github.com/SwissDataScienceCenter/renku-data-services/blob/f3a5f98ef4c29baa147ab2cd6d0c52fb23148a3f/components/renku_data_services/data_connectors/api.spec.yaml#L535-L540

2024-10-07 09:46 UTC, leafty approved these changes
LGTM

2024-10-07 11:27 UTC, merged