refactor: optimize reprovisioning
SwissDataScienceCenter/renku-data-services pull request #458
Opened 2024-10-15 03:25 UTC by m-alisafaee

In this PR, when creating events for various entities from the database, we add all events to a temporary table; once all events are generated, we copy them from the temporary table to the `events` table. This prevents a (possibly) long transaction on the `events` table. It should also improve performance since the temporary table is not logged and has no index and should be faster to write to.

2024-10-17 12:30 UTC, olevski requested changes
Thanks for doing this Mohammad. It looks really good. Just a few questions and suggestions.

2024-10-21 14:57 UTC, m-alisafaee commented on components/renku_data_services/message_queue/core.py
> +                    SELECT queue, payload, timestamp_utc FROM events.events WITH NO DATA
I did an analysis using postgresql's `EXPLAIN` command which shows that the query is `never executed`:
```
EXPLAIN ANALYZE VERBOSE CREATE TABLE foo AS SELECT brand, year FROM bar WITH NO DATA;
                                  QUERY PLAN                                   
-------------------------------------------------------------------------------
 Seq Scan on public.bar  (cost=0.00..10.70 rows=70 width=520) (never executed)
   Output: brand, year
 Planning Time: 1.592 ms
 Execution Time: 6.259 ms
(4 rows)
```

To be safe, I've added a `WHERE FALSE` condition to the query.

2024-10-22 08:49 UTC, olevski submitted a review, later dismissed
Thanks Mohammad. Just resolve the conflicts. I will re-approve again.

2024-10-22 08:53 UTC, olevski submitted a review, later dismissed

2024-10-23 09:38 UTC, olevski approved these changes

2024-10-23 09:39 UTC, merged