chore: move the config into its own component
SwissDataScienceCenter/renku-data-services pull request #91
Opened 2023-11-15 23:48 UTC by olevski

This does a few things:
- reduces (further) the risk that we spawn multiple connection pools (by assigning the connection pool as a class variable on the config class)
- pulls out the `Config` class into its own component - previously it was part of the data services base

2023-11-16 15:22 UTC, olevski commented
This is the followup from #83 @Panaetius

2023-11-16 16:00 UTC, Panaetius requested changes

2023-11-16 16:00 UTC, Panaetius commented on components/renku_data_services/config/config.py
> +    _async_engine_write_lock: ClassVar[asyncio.Lock] = asyncio.Lock()
this isn't used anywhere

2023-11-16 16:00 UTC, Panaetius commented on components/renku_data_services/migrations/env.py
> +    engine.dispose()
I thought we didn't need dispose?

2023-11-17 12:51 UTC, olevski commented on components/renku_data_services/migrations/env.py
> +    engine.dispose()
Yes I forgot we dont need it.

2023-11-17 12:51 UTC, olevski commented on components/renku_data_services/migrations/env.py
> +    engine.dispose()
Removed.

2023-11-17 12:51 UTC, olevski commented on components/renku_data_services/config/config.py
> +    _async_engine_write_lock: ClassVar[asyncio.Lock] = asyncio.Lock()
Removed. I forgot it.

2023-11-17 13:54 UTC, Panaetius approved these changes

2023-11-17 14:04 UTC, merged